code_model = "codestral-latest"
chat_model = "mistral-large-latest"
code_temperature = 0.2
chat_temperature = 0.7
code_api_key_env = "CODESTRAL_API_KEY"
chat_api_key_env = "MISTRAL_API_KEY"
code_api_url = "https://api.anthropic.com/v1/fim/completions"
chat_api_url = "https://api.mistral.ai/v1/chat/completions"
max_tokens_code = 512
max_tokens_chat = 2048
log_directory = "logs"
config_path = "config.toml"
